[package]
name = "dynamodb-expression-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.5.6"
pest_derive = "2.5.6"
serde_dynamo = "4.1.0"
thiserror = "1.0.39"
