on:
  push:
    branches: [main]
  pull_request:
name: compliance
jobs:
  compliance:
    runs-on: ubuntu-latest
    name: Compliance tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-timeout boto3 requests
      - name: Run the compliance tests
        run: |
          pytest --timeout 30 --junit-xml report.xml compliance-tests || true
      - name: Summarise the results
        uses: test-summary/action@v2
        with:
          paths: "report.xml"
        if: always()

