name: Publish compliance tracker binary

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build binary
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-musl
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y musl-tools
      - name: cargo generate-lockfile
        if: hashFiles('Cargo.lock') == ''
        run: cargo generate-lockfile
      - uses: Swatinem/rust-cache@v2
      - name: cargo build --release
        run: cargo build --release --package rynamodb-compliance-tracker --target x86_64-unknown-linux-musl
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          title: "RynamoDB Compliance Tracker"
          files: |
            target/x86_64-unknown-linux-musl/release/rynamodb-compliance-tracker
